name: Deploy Infrastructure and Website

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Prepare Lambda function
        run: |
          mkdir -p lambda
          cat > lambda/basic-auth.js << 'EOF'
          // Basic HTTP Authentication for CloudFront with Lambda@Edge
          'use strict';

          // Configure authentication
          const authUser = 'lcm-user';
          const authPass = ${{ secrets.AUTH_PASSWORD }};

          // Set up the auth string
          const authString = `Basic ${Buffer.from(`${authUser}:${authPass}`).toString('base64')}`;

          exports.handler = (event, context, callback) => {
            // Get the request from the event
            const request = event.Records[0].cf.request;
            const headers = request.headers;

            // Check if the Authorization header exists
            if (headers.authorization) {
              // Get the supplied credentials from the header
              const authValue = headers.authorization[0].value;
              
              // Verify the credentials against our expected values
              if (authValue === authString) {
                // Authentication successful - return the request unchanged
                callback(null, request);
                return;
              }
            }

            // Authentication failed or not provided, return a 401 response
            const response = {
              status: '401',
              statusDescription: 'Unauthorized',
              headers: {
                'www-authenticate': [
                  {
                    key: 'WWW-Authenticate',
                    value: 'Basic realm="Restricted"'
                  }
                ],
                'content-type': [
                  {
                    key: 'Content-Type',
                    value: 'text/html'
                  }
                ]
              },
              body: 'Unauthorized - Authentication Required'
            };

            callback(null, response);
          };
          EOF
          echo "Lambda function file created at lambda/basic-auth.js"

      - name: Initialize Terraform
        run: |
          terraform init \
            -backend-config="bucket=tf-$(aws sts get-caller-identity --query Account --output text)" \
            -backend-config="region=us-east-1"

      - name: Validate Terraform
        run: terraform validate

      - name: Apply Terraform
        run: terraform apply -auto-approve

      - name: Output results
        run: |
          echo "Website deployed at: $(terraform output -raw cloudfront_domain_name)"
          echo "Authentication credentials have been set in the Lambda function" 